### ISSUE TITLE
Feature request: multiple imap accounts

### ISSUE THREAD

**Issue by muescha** [turbot/steampipe-plugin-imap#20]
**Is your feature request related to a problem? Please describe.**

I have multiple imap account which i like to query

**Describe the solution you'd like**

I have a setup file like:

```
connection "imap" {
  account "gmail" {
	  plugin   = "imap"
	  host     = "imap.gmail.com"
	  port     = 993
	  login    = "michael@dundermifflin.com"
	  password = "Great Scott!"
   }
  account "gmx-newsletters" {
	  plugin   = "imap"
	  host     = "imap.gmx.com"
	  port     = 993
	  login    = "newsletters@dundermifflin.com"
	  password = "Great Scott!"
   }
}
```

with 

```
select
  timestamp,
  from_email,
  subject
from
  imap_message
where 
  account = 'gmail';
```

with no `where` part it would query all accounts

```
select
  timestamp,
  from_email,
  subject,
  account
from
  imap_message;
```

**Describe alternatives you've considered**

i need to restart a server with different `imap.spc` or environment variables

**Comment by misraved** [comment]
Hello @muescha, I believe the aggregators can be used to query multiple IMAP accounts.

Please take a look at this documentation - https://steampipe.io/docs/managing/connections#querying-multiple-connections which would help you in creating and managing multiple connections.

Based on the data mentioned in the issue, I think your `imap.spc` file would look something like this - 

```
connection "imap_all" {
  plugin            = "imap"
  type               = "aggregator
  connections  =["imap_gmail", "imap_gmx"]
}

connection "imap_gmail" {
  plugin   = "imap"
  host     = "imap.gmail.com"
  port     = 993
  login    = "michael@dundermifflin.com"
  password = "Great Scott!"
}

connection "imap_gmx" {
  plugin   = "imap"
  host     = "imap.gmx.com"
  port     = 993
  login    = "michael@dundermifflin.com"
  password = "Great Scott!"
}
```

**Comment by bigdatasourav** [comment]
Hey @muescha, did you get a chance to try out the above? Please share if it is working for you now.

**Comment by bigdatasourav** [comment]
Hey @muescha,  I believe the above-proposed solution helped you to resolve the issue you were facing. We are closing the issue now. Please feel free to reopen the issue if you want to share or discuss anything.

**Comment by muescha** [comment]
Thx for pointing to the aggregator solution :)
