### ISSUE TITLE
missing type-specific fields for message/rfc822

### ISSUE THREAD

**Issue by judell** [turbot/steampipe-plugin-imap#3]
Reading an archive of 138K gmail messages, and with the workaround of #2 in place, I get all the way to `seq_num=48985` then the error occurs.

I'm not seeing how to detect it before the message hits `d.streamListItem`. 

I was able to track down the message in my Gmail account, so I have the raw original message, but should transmit it out of band because it's full of names and addresses.

**Comment by e-gineer** [comment]
@judell Can you please share more context / logs around when this error happens? I'm trying to work out where in the imap parsing code etc it's being hit so we can handle it.

**Comment by judell** [comment]
As discussed, it's such a rare thing we can probably just ignore it. 

Something like this seems to work.

```
        if err := <-done; err != nil {
                plugin.Logger(ctx).Error("imap_message.tableIMAPMessageList", "query_error", err, "mailbox", mailbox)
-               return nil, err
+               if fmt.Sprint("%s", err)  == "Missing type-specific fields for message/rfc822" {
+                       return nil, nil
+               } else {
+                       return nil, err
+               }
```

I'll retry the whole archive this way to see how it goes.

**Comment by e-gineer** [comment]
@judell Does this change continue and finish processing all your messages? Or does it stop at the bad message and just avoid failing with an error?

**Comment by judell** [comment]
It continues. But now there's one more `invalid UTF-8` so I need to restart with more aggressive logging to nail that one.

**Comment by judell** [comment]
Well you're right, of course. I was looking at the wrong log. It doesn't continue. The fetch operation seems to be atomic w/respect to the plugin. I can skip the bad message by putting the goroutine in a loop, and doing one fetch at a time, but that's crazy. Is there a way around this that doesn't involve teaching `go-imap` about this particular error?

**Comment by judell** [comment]
I would think that if you ask to fetch a range of seqnums, and one or more throw errors, you could still process the remainder, and receive an array of errors. There's much that I don't yet understand about golang errors in general, and this library in particular, so I'm most likely missing something obvious, @e-gineer. But what?
